// Socket
#define PORT 8888
#define BACKLOG 5
#define BUFFER_SIZE 1024

// Requests
#define MAX_HEADERS 20
#define MAX_HEADER_VALUE_LENGTH 100
#define MAX_HEADER_NAME_LENGTH 30

#define MAX_METHOD_LENGTH 10
#define MAX_URL_LENGTH 200
#define MAX_VERSION_LENGTH 10

// Response

#define MAX_RESPONSE_LENGTH 3000